@echo off
echo Activating virtual environment...
call pdf_tools_env\Scripts\activate.bat
echo Installing any missing dependencies...
pip install -r requirements.txt
echo Starting PDF Tools...
streamlit run pdf_tools/app.py
pause